### ISSUE TITLE
illustrator ios template looks like the slices aren't set

### ISSUE THREAD

**Issue by sonoflin** [bjango/Bjango-Templates#6]
First of all, thanks for these templates, they are great.  I am attempting to use the Illustrator Appleios template but it looks like no slices have been pre configured.  Is this user error or is there a newer file that has the slices?

Thanks much,

-Ian

**Comment by marcedwards** [comment]
Cheers. :D 

The `App Icon - Apple iOS.ai` now uses the new Asset Export method. It’s currently the only Illustrator template in the collection to do that. I’m experimenting to work out the best setup for exporting, because it seems likely that slices will be deprecated at some point.

My apologies for not documenting this in the help. I was hoping to convert all the Illustrator templates and then fix the help. I’m not yet convinced the Asset Export panel is better though. If nothing else, updating the artwork can break the exporting setup (depending on what you change).

<img width="247" alt="screen shot 2018-07-24 at 4 09 26 pm" src="https://user-images.githubusercontent.com/1121547/43120049-339c22e2-8f5c-11e8-965e-dee2b414f2e9.png">

**Comment by sonoflin** [comment]
Thanks for the reply, much appreciated
